#include "simulation_data.h"
#include "util/real_array.h"

OMC_DISABLE_OPT

void Tank_read_simulation_info(SIMULATION_INFO* simulationInfo)
{
  simulationInfo->startTime = 0.0;
  simulationInfo->stopTime = 1.0;
  simulationInfo->stepSize = 0.002;
  simulationInfo->tolerance = 1e-6;
  simulationInfo->solverMethod = "dassl";
  simulationInfo->outputFormat = "mat";
  simulationInfo->variableFilter = ".*";
  simulationInfo->OPENMODELICAHOME = "/usr/bin/..";
}

void Tank_read_input_fmu(MODEL_DATA* modelData)
{
  modelData->realVarsData[0].info.id = 1000;
  modelData->realVarsData[0].info.name = "h";
  modelData->realVarsData[0].info.comment = "уровень, м";
  modelData->realVarsData[0].info.info.filename = ".";
  modelData->realVarsData[0].info.info.lineStart = 12;
  modelData->realVarsData[0].info.info.colStart = 3;
  modelData->realVarsData[0].info.info.lineEnd = 12;
  modelData->realVarsData[0].info.info.colEnd = 57;
  modelData->realVarsData[0].info.info.readonly = 0;
  modelData->realVarsData[0].attribute.unit = "";
  modelData->realVarsData[0].attribute.displayUnit = "";
  put_real_element(-DBL_MAX, 0, &modelData->realVarsData[0].attribute.min);
  put_real_element(DBL_MAX, 0, &modelData->realVarsData[0].attribute.max);
  modelData->realVarsData[0].attribute.fixed = 1;
  modelData->realVarsData[0].attribute.useNominal = 0;
  put_real_element(1.0, 0, &modelData->realVarsData[0].attribute.nominal);
  put_real_element(0.0, 0, &modelData->realVarsData[0].attribute.start);
  modelData->realVarsData[1].info.id = 1001;
  modelData->realVarsData[1].info.name = "der(h)";
  modelData->realVarsData[1].info.comment = "der(уровень, м)";
  modelData->realVarsData[1].info.info.filename = ".";
  modelData->realVarsData[1].info.info.lineStart = 12;
  modelData->realVarsData[1].info.info.colStart = 3;
  modelData->realVarsData[1].info.info.lineEnd = 12;
  modelData->realVarsData[1].info.info.colEnd = 57;
  modelData->realVarsData[1].info.info.readonly = 0;
  modelData->realVarsData[1].attribute.unit = "";
  modelData->realVarsData[1].attribute.displayUnit = "";
  put_real_element(-DBL_MAX, 0, &modelData->realVarsData[1].attribute.min);
  put_real_element(DBL_MAX, 0, &modelData->realVarsData[1].attribute.max);
  modelData->realVarsData[1].attribute.fixed = 0;
  modelData->realVarsData[1].attribute.useNominal = 0;
  put_real_element(1.0, 0, &modelData->realVarsData[1].attribute.nominal);
  put_real_element(0.0, 0, &modelData->realVarsData[1].attribute.start);
  modelData->realVarsData[2].info.id = 1002;
  modelData->realVarsData[2].info.name = "height";
  modelData->realVarsData[2].info.comment = "уровень, м";
  modelData->realVarsData[2].info.info.filename = ".";
  modelData->realVarsData[2].info.info.lineStart = 14;
  modelData->realVarsData[2].info.info.colStart = 3;
  modelData->realVarsData[2].info.info.lineEnd = 14;
  modelData->realVarsData[2].info.info.colEnd = 52;
  modelData->realVarsData[2].info.info.readonly = 0;
  modelData->realVarsData[2].attribute.unit = "";
  modelData->realVarsData[2].attribute.displayUnit = "";
  put_real_element(-DBL_MAX, 0, &modelData->realVarsData[2].attribute.min);
  put_real_element(DBL_MAX, 0, &modelData->realVarsData[2].attribute.max);
  modelData->realVarsData[2].attribute.fixed = 0;
  modelData->realVarsData[2].attribute.useNominal = 0;
  put_real_element(1.0, 0, &modelData->realVarsData[2].attribute.nominal);
  put_real_element(0.0, 0, &modelData->realVarsData[2].attribute.start);
  modelData->realVarsData[3].info.id = 1003;
  modelData->realVarsData[3].info.name = "u";
  modelData->realVarsData[3].info.comment = "насос 0/1";
  modelData->realVarsData[3].info.info.filename = ".";
  modelData->realVarsData[3].info.info.lineStart = 13;
  modelData->realVarsData[3].info.info.colStart = 3;
  modelData->realVarsData[3].info.info.lineEnd = 13;
  modelData->realVarsData[3].info.info.colEnd = 42;
  modelData->realVarsData[3].info.info.readonly = 0;
  modelData->realVarsData[3].attribute.unit = "";
  modelData->realVarsData[3].attribute.displayUnit = "";
  put_real_element(-DBL_MAX, 0, &modelData->realVarsData[3].attribute.min);
  put_real_element(DBL_MAX, 0, &modelData->realVarsData[3].attribute.max);
  modelData->realVarsData[3].attribute.fixed = 1;
  modelData->realVarsData[3].attribute.useNominal = 0;
  put_real_element(1.0, 0, &modelData->realVarsData[3].attribute.nominal);
  put_real_element(0.0, 0, &modelData->realVarsData[3].attribute.start);
  modelData->realParameterData[0].info.id = 1004;
  modelData->realParameterData[0].info.name = "A";
  modelData->realParameterData[0].info.comment = "площадь сечения, м2";
  modelData->realParameterData[0].info.info.filename = ".";
  modelData->realParameterData[0].info.info.lineStart = 9;
  modelData->realParameterData[0].info.info.colStart = 3;
  modelData->realParameterData[0].info.info.lineEnd = 9;
  modelData->realParameterData[0].info.info.colEnd = 62;
  modelData->realParameterData[0].info.info.readonly = 0;
  modelData->realParameterData[0].attribute.unit = "";
  modelData->realParameterData[0].attribute.displayUnit = "";
  put_real_element(-DBL_MAX, 0, &modelData->realParameterData[0].attribute.min);
  put_real_element(DBL_MAX, 0, &modelData->realParameterData[0].attribute.max);
  modelData->realParameterData[0].attribute.fixed = 1;
  modelData->realParameterData[0].attribute.useNominal = 0;
  put_real_element(1.0, 0, &modelData->realParameterData[0].attribute.nominal);
  put_real_element(1.0, 0, &modelData->realParameterData[0].attribute.start);
  modelData->realParameterData[1].info.id = 1005;
  modelData->realParameterData[1].info.name = "Qin";
  modelData->realParameterData[1].info.comment = "подача насоса, м3/с";
  modelData->realParameterData[1].info.info.filename = ".";
  modelData->realParameterData[1].info.info.lineStart = 10;
  modelData->realParameterData[1].info.info.colStart = 3;
  modelData->realParameterData[1].info.info.lineEnd = 10;
  modelData->realParameterData[1].info.info.colEnd = 63;
  modelData->realParameterData[1].info.info.readonly = 0;
  modelData->realParameterData[1].attribute.unit = "";
  modelData->realParameterData[1].attribute.displayUnit = "";
  put_real_element(-DBL_MAX, 0, &modelData->realParameterData[1].attribute.min);
  put_real_element(DBL_MAX, 0, &modelData->realParameterData[1].attribute.max);
  modelData->realParameterData[1].attribute.fixed = 1;
  modelData->realParameterData[1].attribute.useNominal = 0;
  put_real_element(1.0, 0, &modelData->realParameterData[1].attribute.nominal);
  put_real_element(1.5, 0, &modelData->realParameterData[1].attribute.start);
  modelData->realParameterData[2].info.id = 1006;
  modelData->realParameterData[2].info.name = "Qout";
  modelData->realParameterData[2].info.comment = "слив, м3/с";
  modelData->realParameterData[2].info.info.filename = ".";
  modelData->realParameterData[2].info.info.lineStart = 11;
  modelData->realParameterData[2].info.info.colStart = 3;
  modelData->realParameterData[2].info.info.lineEnd = 11;
  modelData->realParameterData[2].info.info.colEnd = 47;
  modelData->realParameterData[2].info.info.readonly = 0;
  modelData->realParameterData[2].attribute.unit = "";
  modelData->realParameterData[2].attribute.displayUnit = "";
  put_real_element(-DBL_MAX, 0, &modelData->realParameterData[2].attribute.min);
  put_real_element(DBL_MAX, 0, &modelData->realParameterData[2].attribute.max);
  modelData->realParameterData[2].attribute.fixed = 1;
  modelData->realParameterData[2].attribute.useNominal = 0;
  put_real_element(1.0, 0, &modelData->realParameterData[2].attribute.nominal);
  put_real_element(0.5, 0, &modelData->realParameterData[2].attribute.start);
}