/* Simulation code for TwoStandMill generated by the OpenModelica Compiler OpenModelica 1.27.0~5-ga0783c0. */
#if !defined(TwoStandMill__MODEL_H)
#define TwoStandMill__MODEL_H

#if defined(__cplusplus)
extern "C" {
#endif

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "simulation/jacobian_util.h"
#include "simulation/simulation_omc_assert.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"
#include "simulation/solver/spatialDistribution.h"
#include "simulation/solver/synchronous.h"

#include <string.h>

#include "TwoStandMill_functions.h"


extern void TwoStandMill_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
extern void TwoStandMill_initialNonLinearSystem(int nNonLinearSystems, NONLINEAR_SYSTEM_DATA *data);
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void TwoStandMill_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int TwoStandMill_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int TwoStandMill_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int TwoStandMill_function_storeSpatialDistribution(DATA *data, threadData_t *threadData);
extern int TwoStandMill_function_initSpatialDistribution(DATA *data, threadData_t *threadData);
extern int TwoStandMill_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int TwoStandMill_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int TwoStandMill_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int TwoStandMill_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int TwoStandMill_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int TwoStandMill_checkForAsserts(DATA *data, threadData_t *threadData);
extern int TwoStandMill_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int TwoStandMill_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int TwoStandMill_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* TwoStandMill_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* TwoStandMill_relationDescription(int i);
extern void TwoStandMill_function_initSample(DATA *data, threadData_t *threadData);
extern int TwoStandMill_initialAnalyticJacobianG(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int TwoStandMill_initialAnalyticJacobianA(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int TwoStandMill_initialAnalyticJacobianADJ(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int TwoStandMill_initialAnalyticJacobianB(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int TwoStandMill_initialAnalyticJacobianC(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int TwoStandMill_initialAnalyticJacobianD(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int TwoStandMill_initialAnalyticJacobianF(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int TwoStandMill_initialAnalyticJacobianH(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int TwoStandMill_functionJacG_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int TwoStandMill_functionJacA_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int TwoStandMill_functionJacADJ_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int TwoStandMill_functionJacB_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int TwoStandMill_functionJacC_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int TwoStandMill_functionJacD_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int TwoStandMill_functionJacF_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int TwoStandMill_functionJacH_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern const char* TwoStandMill_linear_model_frame(void);
extern const char* TwoStandMill_linear_model_datarecovery_frame(void);
extern int TwoStandMill_mayer(DATA* data, modelica_real** res, short *);
extern int TwoStandMill_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int TwoStandMill_getInputVarIndicesInOptimization(DATA* data, int* input_var_indices);
extern int TwoStandMill_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int TwoStandMill_setInputData(DATA *data, const modelica_boolean file);
extern int TwoStandMill_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void TwoStandMill_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void TwoStandMill_function_updateSynchronous(DATA * data, threadData_t *threadData, long base_idx);
extern int TwoStandMill_function_equationsSynchronous(DATA * data, threadData_t *threadData, long base_idx, long sub_idx);
extern void TwoStandMill_read_simulation_info(SIMULATION_INFO* simulationData);
extern void TwoStandMill_read_input_fmu(MODEL_DATA* modelData);
extern void TwoStandMill_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int TwoStandMill_inputNames(DATA* data, char ** names);
extern int TwoStandMill_dataReconciliationInputNames(DATA* data, char ** names);
extern int TwoStandMill_dataReconciliationUnmeasuredVariables(DATA* data, char ** names);
extern int TwoStandMill_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int TwoStandMill_functionLocalKnownVars(DATA* data, threadData_t* threadData);
extern int TwoStandMill_symbolicInlineSystem(DATA* data, threadData_t* threadData);

#include "TwoStandMill_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(TwoStandMill__MODEL_H) */


